import "./globals.css";
import { Navbar10 } from "@/components/navbar-10";
import { Footer13 } from "@/components/footer-13";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Navbar10 />
        {children}
        <Footer13 />
      </body>
    </html>
  );
}
